### ISSUE TITLE
Create Firestore Db of 243 Movies

### ISSUE THREAD

**Issue by Fahimansari** [Fahimansari/flickfindz#15]
#### Tasks

- [x] Create the possible combinations.
- [x] Create an Array of 6 movies for every possible search combination
- [ ] Create an Array of the Movie DB
- [ ] Use a script to add the files in that array into the Firestore DB

#### Description
- Each movie should have a Name, description and an image URL
- Document Structure
```
{
id : (auto-generated)
name: string,
tag: array,
description: string,
imageURL: string
}
```
